//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoHUD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logo:0,0|CPURAM:5,0|IP:9,0|NET:9,1|Clock:55,0|RSS:25,0|Date:17,1|User:17,0")]
        public string HUDObjects {
            get {
                return ((string)(this["HUDObjects"]));
            }
            set {
                this["HUDObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 2")]
        public global::System.Drawing.Size HUDSize {
            get {
                return ((global::System.Drawing.Size)(this["HUDSize"]));
            }
            set {
                this["HUDSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intel[R] Wireless WiFi Link 4965AGN")]
        public string IONETInterface {
            get {
                return ((string)(this["IONETInterface"]));
            }
            set {
                this["IONETInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://index.hu/24ora/rss/</string>
  <string>http://rss.groups.yahoo.com/group/mechatronika20082009m2/rss</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IORSSFeeds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IORSSFeeds"]));
            }
            set {
                this["IORSSFeeds"] = value;
            }
        }
    }
}
